export default {
  serverURI: '',
  apiGetVmSize: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetVmSize',
  apiGetVmSizes: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetVmSizes',
  apiGetRegions: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetRegions',
  apiGetVmDetail: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetVmDetail',
  apiCalcVmOptimizations: 'http://api-dev-vmchooser-com.trafficmanager.net/api/CalcVmOptimizations',
  apiGetDiskConfig: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetDiskConfig',
  apiGetSqlService: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetSqlService',
  apiGetSqlServiceStorage: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetSqlServiceStorage',
  apiGetBackup: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetBackup',
  apiGetCloudSimple: 'http://api-dev-vmchooser-com.trafficmanager.net/api/GetCloudSimple',
  apiKey: '',
  fixedLayout: false,
  hideLogoOnMobile: false,
  clientId: 'f4b67345-011d-4b77-b746-05e152a61812',
  redirectUri: 'https://www.vmchooser.com/',
  tenant: 'common',
  appinsightsid: '15aa612c-5481-43b2-98a9-0596a63d9e6f'
}
