export default {
  serverURI: '',
  apiGetVmSize: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetVmSize',
  apiGetVmSizes: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetVmSizes',
  apiGetRegions: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetRegions',
  apiGetVmDetail: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetVmDetail',
  apiCalcVmOptimizations: 'http://api-prd-vmchooser-com.trafficmanager.net/api/CalcVmOptimizations',
  apiGetDiskConfig: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetDiskConfig',
  apiGetSqlService: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetSqlService',
  apiGetSqlServiceStorage: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetSqlServiceStorage',
  apiGetBackup: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetBackup',
  apiGetCloudSimple: 'http://api-prd-vmchooser-com.trafficmanager.net/api/GetCloudSimple',
  apiKey: '',
  fixedLayout: false,
  hideLogoOnMobile: false,
  clientId: 'f4b67345-011d-4b77-b746-05e152a61812',
  redirectUri: 'https://www.vmchooser.com/',
  tenant: 'common',
  appinsightsid: '0e8aa1e6-c2dd-4aaf-8473-f0006d6b3425'
}
