export default {
  serverURI: '',
  apiGetVmSize: 'https://be-prd.vmchooser.com/api/GetVmSize',
  apiGetVmSizes: 'https://be-prd.vmchooser.com/api/GetVmSizes',
  apiGetRegions: 'https://be-prd.vmchooser.com/api/GetRegions',
  apiGetVmDetail: 'https://be-prd.vmchooser.com/api/GetVmDetail',
  apiCalcVmOptimizations: 'https://be-prd.vmchooser.com/api/CalcVmOptimizations',
  apiGetDiskConfig: 'https://be-prd.vmchooser.com/api/GetDiskConfig',
  apiGetSqlService: 'https://be-prd.vmchooser.com/api/GetSqlService',
  apiGetSqlServiceStorage: 'https://be-prd.vmchooser.com/api/GetSqlServiceStorage',
  apiGetBackup: 'https://be-prd.vmchooser.com/api/GetBackup',
  apiGetCloudSimple: 'https://be-prd.vmchooser.com/api/GetCloudSimple',
  apiGetAroWorkers: 'https://be-prd.vmchooser.com/api/GetAroWorkers',
  apiKey: '',
  fixedLayout: false,
  hideLogoOnMobile: false,
  clientId: 'f4b67345-011d-4b77-b746-05e152a61812',
  redirectUri: 'https://www.vmchooser.com/',
  tenant: 'common',
  appinsightsid: '0e8aa1e6-c2dd-4aaf-8473-f0006d6b3425'
}
