export default {
  serverURI: '',
  apiGetVmSize: 'http://'+process.env.API_HOSTNAME+'/api/GetVmSize',
  apiGetVmSizes: 'http://'+process.env.API_HOSTNAME+'/api/GetVmSizes',
  apiGetRegions: 'http://'+process.env.API_HOSTNAME+'/api/GetRegions',
  apiGetVmDetail: 'http://'+process.env.API_HOSTNAME+'/api/GetVmDetail',
  apiCalcVmOptimizations: 'http://'+process.env.API_HOSTNAME+'/api/CalcVmOptimizations',
  apiGetDiskConfig: 'http://'+process.env.API_HOSTNAME+'/api/GetDiskConfig',
  apiGetSqlService: 'http://'+process.env.API_HOSTNAME+'/api/GetSqlService',
  apiGetSqlServiceStorage: 'http://'+process.env.API_HOSTNAME+'/api/GetSqlServiceStorage',
  apiGetBackup: 'http://'+process.env.API_HOSTNAME+'/api/GetBackup',
  apiGetCloudSimple: 'http://'+process.env.API_HOSTNAME+'/api/GetCloudSimple',
  apiKey: '',
  fixedLayout: false,
  hideLogoOnMobile: false,
  clientId: 'f4b67345-011d-4b77-b746-05e152a61812',
  redirectUri: 'https://www.vmchooser.com/',
  tenant: 'common',
  appinsightsid: process.env.APPINSIGHTS_INSTRUMENTATIONKEY
}
