export default {
  serverURI: '',
  apiGetVmSize: 'https://vmchooserprod.azurewebsites.net/api/GetVmSize',
  apiGetVmSizes: 'https://vmchooserprod.azurewebsites.net/api/GetVmSizes',
  apiGetRegions: 'https://vmchooserprod.azurewebsites.net/api/GetRegions',
  apiGetVmDetail: 'https://vmchooserprod.azurewebsites.net/api/GetVmDetail',
  apiCalcVmOptimizations: 'https://vmchooserprod.azurewebsites.net/api/CalcVmOptimizations',
  apiGetDiskConfig: 'https://vmchooserprod.azurewebsites.net/api/GetDiskConfig',
  apiGetSqlService: 'https://vmchooserprod.azurewebsites.net/api/GetSqlService',
  apiGetSqlServiceStorage: 'https://vmchooserprod.azurewebsites.net/api/GetSqlServiceStorage',
  apiGetBackup: 'https://vmchooserprod.azurewebsites.net/api/GetBackup',
  apiGetCloudSimple: 'https://vmchooserprod.azurewebsites.net/api/GetCloudSimple',
  apiKey: '',
  fixedLayout: false,
  hideLogoOnMobile: false,
  clientId: 'f4b67345-011d-4b77-b746-05e152a61812',
  redirectUri: 'https://www.vmchooser.com/',
  tenant: 'common',
  appinsightsid: process.env.APPINSIGHTS_INSTRUMENTATIONKEY
}
